params:
  sp_type: "biorad_96_wellplate_200ul_pcr"
  tp_type: "biorad_96_wellplate_200ul_pcr"
  dp_type: "biorad_96_wellplate_200ul_pcr"
  tube_rack: "opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap"
  buf_vol: 1000.0
  min_vol: 2.0
  max_vol: 100.0
  max_dil: 20.0
  min_fin: 20.0
  pspeed: 24.0
  mix_times: 4
csv:
  uploaded_csv: "data.csv"
