params:
  plate_type: "biorad_96_wellplate_200ul_pcr"
  tube_rack: "opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap"
  res_vol: 1000.0
  min_vol: 2.0
  max_vol: 100.0
  pspeed: 7.56
csv:
  uploaded_csv: "data.csv"
